<?php

 $languages = [
	 [
		 "english_name" => "French",
		 "native_name" => "Français",
		 "code" => "fr",
		 "locale" => "fr_FR",
		 "tag" => "fr",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Arabic",
		 "native_name" => "العربية",
		 "code" => "ar",
		 "locale" => "ar",
		 "tag" => "ar",
		 "rtl" => 1,
	 ],
	 [
		 "english_name" => "Kazakh",
		 "native_name" => "Қазақ",
		 "code" => "kaz",
		 "locale" => "kk",
		 "tag" => "kk-KZ",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Abkhaz",
		 "native_name" => "Abkhaz",
		 "code" => "ab",
		 "locale" => "ab",
		 "tag" => "ab",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Serbian",
		 "native_name" => "српски",
		 "code" => "sr",
		 "locale" => "sr_RS",
		 "tag" => "sr",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Hindi",
		 "native_name" => "हिन्दी",
		 "code" => "hi",
		 "locale" => "hi_IN",
		 "tag" => "hi",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Greek",
		 "native_name" => "Ελληνικά",
		 "code" => "el",
		 "locale" => "el",
		 "tag" => "el",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Chinese (Traditional)",
		 "native_name" => "繁體中文",
		 "code" => "zh-hant",
		 "locale" => "zh_TW",
		 "tag" => "zh-hant",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Spanish",
		 "native_name" => "Español",
		 "code" => "es",
		 "locale" => "es_ES",
		 "tag" => "es",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "German",
		 "native_name" => "Deutsch",
		 "code" => "de",
		 "locale" => "de_DE",
		 "tag" => "de",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Bosnian",
		 "native_name" => "Bosnian",
		 "code" => "bs",
		 "locale" => "bs_BA",
		 "tag" => "bs",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Bulgarian",
		 "native_name" => "Български",
		 "code" => "bg",
		 "locale" => "bg_BG",
		 "tag" => "bg",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Catalan",
		 "native_name" => "Català",
		 "code" => "ca",
		 "locale" => "ca",
		 "tag" => "ca",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Czech",
		 "native_name" => "Čeština",
		 "code" => "cs",
		 "locale" => "cs_CZ",
		 "tag" => "cs",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Slovak",
		 "native_name" => "Slovenčina",
		 "code" => "sk",
		 "locale" => "sk_SK",
		 "tag" => "sk",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Welsh",
		 "native_name" => "Cymraeg",
		 "code" => "cy",
		 "locale" => "cy_GB",
		 "tag" => "cy",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Danish",
		 "native_name" => "Dansk",
		 "code" => "da",
		 "locale" => "da_DK",
		 "tag" => "da",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Esperanto",
		 "native_name" => "Esperanta",
		 "code" => "eo",
		 "locale" => "eo_UY",
		 "tag" => "eo",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Estonian",
		 "native_name" => "Eesti",
		 "code" => "et",
		 "locale" => "et",
		 "tag" => "et",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Basque",
		 "native_name" => "Euskara",
		 "code" => "eu",
		 "locale" => "eu_ES",
		 "tag" => "eu",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Persian",
		 "native_name" => "فارسی",
		 "code" => "fa",
		 "locale" => "fa_IR",
		 "tag" => "fa",
		 "rtl" => 1,
	 ],
	 [
		 "english_name" => "Finnish",
		 "native_name" => "Suomi",
		 "code" => "fi",
		 "locale" => "fi",
		 "tag" => "fi",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Irish",
		 "native_name" => "Gaeilge",
		 "code" => "ga",
		 "locale" => "ga_IE",
		 "tag" => "ga",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Hebrew",
		 "native_name" => "עברית",
		 "code" => "he",
		 "locale" => "he_IL",
		 "tag" => "he",
		 "rtl" => 1,
	 ],
	 [
		 "english_name" => "Croatian",
		 "native_name" => "Hrvatski",
		 "code" => "hr",
		 "locale" => "hr",
		 "tag" => "hr",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Hungarian",
		 "native_name" => "Magyar",
		 "code" => "hu",
		 "locale" => "hu_HU",
		 "tag" => "hu",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Armenian",
		 "native_name" => "Հայերեն",
		 "code" => "hy",
		 "locale" => "hy_AM",
		 "tag" => "hy",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Indonesian",
		 "native_name" => "Indonesia",
		 "code" => "id",
		 "locale" => "id_ID",
		 "tag" => "id",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Icelandic",
		 "native_name" => "Íslenska",
		 "code" => "is",
		 "locale" => "is_IS",
		 "tag" => "is",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Italian",
		 "native_name" => "Italiano",
		 "code" => "it",
		 "locale" => "it_IT",
		 "tag" => "it",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Japanese",
		 "native_name" => "日本語",
		 "code" => "ja",
		 "locale" => "ja",
		 "tag" => "ja",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Korean",
		 "native_name" => "한국어",
		 "code" => "ko",
		 "locale" => "ko_KR",
		 "tag" => "ko",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Kurdish",
		 "native_name" => "Kurdish",
		 "code" => "ku",
		 "locale" => "ckb",
		 "tag" => "ku",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Latvian",
		 "native_name" => "Latviešu",
		 "code" => "lv",
		 "locale" => "lv_LV",
		 "tag" => "lv",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Lithuanian",
		 "native_name" => "Lietuvių",
		 "code" => "lt",
		 "locale" => "lt_LT",
		 "tag" => "lt",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Macedonian",
		 "native_name" => "македонски",
		 "code" => "mk",
		 "locale" => "mk_MK",
		 "tag" => "mk",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Maltese",
		 "native_name" => "Malti",
		 "code" => "mt",
		 "locale" => "mt_MT",
		 "tag" => "mt",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Mongolian",
		 "native_name" => "Mongolian",
		 "code" => "mn",
		 "locale" => "mn_MN",
		 "tag" => "mn",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Nepali",
		 "native_name" => "Nepali",
		 "code" => "ne",
		 "locale" => "ne",
		 "tag" => "ne",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Dutch",
		 "native_name" => "Nederlands",
		 "code" => "nl",
		 "locale" => "nl_NL",
		 "tag" => "nl",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Norwegian Bokmål",
		 "native_name" => "Norsk bokmål",
		 "code" => "no",
		 "locale" => "nb_NO",
		 "tag" => "no",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Punjabi",
		 "native_name" => "Punjabi",
		 "code" => "pa",
		 "locale" => "pa_IN",
		 "tag" => "pa",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Polish",
		 "native_name" => "Polski",
		 "code" => "pl",
		 "locale" => "pl_PL",
		 "tag" => "pl",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Portuguese, Portugal",
		 "native_name" => "Português",
		 "code" => "pt-pt",
		 "locale" => "pt_PT",
		 "tag" => "pt-pt",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Portuguese, Brazil",
		 "native_name" => "Português",
		 "code" => "pt-br",
		 "locale" => "pt_BR",
		 "tag" => "pt-br",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Quechua",
		 "native_name" => "Quechua",
		 "code" => "qu",
		 "locale" => "quz_PE",
		 "tag" => "qu",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Romanian",
		 "native_name" => "Română",
		 "code" => "ro",
		 "locale" => "ro_RO",
		 "tag" => "ro",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Slovenian",
		 "native_name" => "Slovenščina",
		 "code" => "sl",
		 "locale" => "sl_SI",
		 "tag" => "sl",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Somali",
		 "native_name" => "Somali",
		 "code" => "so",
		 "locale" => "so_SO",
		 "tag" => "so",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Albanian",
		 "native_name" => "Albanian",
		 "code" => "sq",
		 "locale" => "sq_AL",
		 "tag" => "sq",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Swedish",
		 "native_name" => "Svenska",
		 "code" => "sv",
		 "locale" => "sv_SE",
		 "tag" => "sv",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Tamil",
		 "native_name" => "Tamil",
		 "code" => "ta",
		 "locale" => "ta_IN",
		 "tag" => "ta",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Thai",
		 "native_name" => "ไทย",
		 "code" => "th",
		 "locale" => "th",
		 "tag" => "th",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Turkish",
		 "native_name" => "Türkçe",
		 "code" => "tr",
		 "locale" => "tr_TR",
		 "tag" => "tr",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Ukrainian",
		 "native_name" => "Українська",
		 "code" => "uk",
		 "locale" => "uk",
		 "tag" => "uk",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Urdu",
		 "native_name" => "اردو ",
		 "code" => "ur",
		 "locale" => "ur",
		 "tag" => "ur",
		 "rtl" => 1,
	 ],
	 [
		 "english_name" => "Uzbek",
		 "native_name" => "Uzbek",
		 "code" => "uz",
		 "locale" => "uz_UZ",
		 "tag" => "uz",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Vietnamese",
		 "native_name" => "Tiếng Việt",
		 "code" => "vi",
		 "locale" => "vi_VN",
		 "tag" => "vi",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Yiddish",
		 "native_name" => "Yiddish",
		 "code" => "yi",
		 "locale" => "",
		 "tag" => "yi",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Chinese (Simplified)",
		 "native_name" => "简体中文",
		 "code" => "zh-hans",
		 "locale" => "zh_CN",
		 "tag" => "zh-hans",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Zulu",
		 "native_name" => "Zulu",
		 "code" => "zu",
		 "locale" => "",
		 "tag" => "zu",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Malay",
		 "native_name" => "Melayu",
		 "code" => "ms",
		 "locale" => "ms_MY",
		 "tag" => "ms",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Galician",
		 "native_name" => "Galego",
		 "code" => "gl",
		 "locale" => "gl_ES",
		 "tag" => "gl",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Bengali",
		 "native_name" => "বাংলাদেশ",
		 "code" => "bn",
		 "locale" => "bn_BD",
		 "tag" => "bn",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Azerbaijani",
		 "native_name" => "Azərbaycan",
		 "code" => "az",
		 "locale" => "az",
		 "tag" => "az",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "Russian",
		 "native_name" => "Русский",
		 "code" => "ru",
		 "locale" => "ru_RU",
		 "tag" => "ru",
		 "rtl" => 0,
	 ],
	 [
		 "english_name" => "English",
		 "native_name" => "English",
		 "code" => "en",
		 "locale" => "en_US",
		 "tag" => "en",
		 "rtl" => 0,
	 ]
 ];
